name: Docker Python CI

# This section defines the events that will trigger the workflow
on:
  push:
    branches:
      - main           # Trigger on push to main branch
      - feature/*      # Trigger on push to any branch starting with "feature/"
  pull_request:
    branches:
      - main           # Trigger on pull requests targeting the main branch
      - feature/*      # Trigger on pull requests targeting any "feature/*" branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest  # The type of runner that will execute the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out the repository's code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for multi-platform builds

    - name: Cache Docker layers
      uses: actions/cache@v3  # Caches Docker layers to speed up builds
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2  # Logs in to GitHub Container Registry
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t python-docker-vscode .  # Builds the Docker image

    - name: Run Docker container
      run: docker run python-docker-vscode  # Runs the Docker container with the built image

    - name: Verify output
      run: |
        docker run python-docker-vscode > output.txt
        cat output.txt  # Captures and prints the output of the Docker container